ALTER TABLE `CONTACT_TYPE` ADD COLUMN `UUID` varchar(255) COLLATE utf8_bin NOT NULL;
ALTER TABLE `USER_CONTACT` ADD COLUMN `UUID` varchar(255) COLLATE utf8_bin NOT NULL;

UPDATE `CONTACT_TYPE` SET `UUID` = uuid();
UPDATE `USER_CONTACT` SET `UUID` = uuid();