CREATE TABLE `LAST_READ_POSTS` (
  `TOPIC_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `LAST_READ_POST_INDEX` int(11) NOT NULL,
  CONSTRAINT `FK_USER_READ_POSTS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`),
  CONSTRAINT `FK_TOPIC_READ_POSTS` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
