ALTER TABLE LAST_READ_POSTS
DROP FOREIGN KEY `FK_USER_READ_POSTS`,
DROP FOREIGN KEY `FK_TOPIC_READ_POSTS`;
ALTER TABLE LAST_READ_POSTS
ADD CONSTRAINT `FK_USER_READ_POSTS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE,
ADD CONSTRAINT `FK_TOPIC_READ_POSTS` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`) ON DELETE CASCADE;