INSERT INTO `SECTIONS`(`SECTION_ID`, `UUID`, `NAME`, `DESCRIPTION`, `POSITION`)
	SELECT `SECTION_ID`, `UUID`, `NAME`, `DESCRIPTION`, `POSITION`  FROM `SECTION`;

INSERT INTO `BRANCHES`(`BRANCH_ID`, `UUID`, `NAME`, `DESCRIPTION`, `POSITION`, `SECTION_ID`)
	SELECT `BRANCH_ID`, `UUID`, `NAME`, `DESCRIPTION`, `BRANCHES_INDEX`, `SECTION_ID` FROM `BRANCH`;

ALTER TABLE `TOPIC`
	DROP FOREIGN KEY `FK_BRANCH`;

ALTER TABLE `BRANCH`
	DROP FOREIGN KEY `FK_SECTION_REF`;

ALTER TABLE `BRANCH_SUBSCRIPTIONS`
	DROP FOREIGN KEY `FK_BRANCH_SUB`;

DROP TABLE `SECTION`;

DROP TABLE `BRANCH`;

ALTER TABLE `TOPIC`
    ADD CONSTRAINT `FK_BRANCH` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCHES` (`BRANCH_ID`);

ALTER TABLE `BRANCH_SUBSCRIPTIONS`
    ADD CONSTRAINT `FK_BRANCH_SUB` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCHES` (`BRANCH_ID`);





