CREATE TABLE `TOPIC_SUBSCRIPTIONS` (
  `TOPIC_ID` bigint(20) NOT NULL,
  `USER_ID`  bigint(20) NOT NULL,
  KEY `FK_USER` (`USER_ID`),
  KEY `FK_TOPIC` (`TOPIC_ID`),
  CONSTRAINT `FK_TOPIC_SUB` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`),
  CONSTRAINT `FK_USER_TOPIC_SUB` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `BRANCH_SUBSCRIPTIONS` (
  `BRANCH_ID` bigint(20) NOT NULL,
  `USER_ID`  bigint(20) NOT NULL,
  KEY `FK_USER` (`USER_ID`),
  KEY `FK_BRANCH` (`BRANCH_ID`),
  CONSTRAINT `FK_BRANCH_SUB` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCH` (`BRANCH_ID`),
  CONSTRAINT `FK_USER_BRANCH_SUB` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB;