CREATE TABLE `VOTINGS` (
  `VOTING_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
  `ENDING_DATE` datetime,
  `SINGLE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`VOTING_ID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `VOTING_OPTIONS` (
  `VO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `NAME` varchar(255) COLLATE utf8_bin NOT NULL,
  `VOTE_COUNT` int(11) NOT NULL DEFAULT '0',
  `VOTING_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`VO_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_VOTING` (`VOTING_ID`),
  CONSTRAINT `FK_VOTING` FOREIGN KEY (`VOTING_ID`) REFERENCES `VOTINGS` (`VOTING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `TOPIC`
	ADD COLUMN `VOTING_ID` bigint(20) DEFAULT NULL;
ALTER TABLE `TOPIC`	
	ADD CONSTRAINT `FK_TOPIC_VOTING` FOREIGN KEY (`VOTING_ID`) REFERENCES `VOTINGS` (`VOTING_ID`);