ALTER TABLE CONTACT_TYPE 
    ADD MASK VARCHAR(50) NOT NULL DEFAULT '',
    ADD DISPLAY_PATTERN VARCHAR(50) NOT NULL DEFAULT '${contact}',
    ADD VALIDATION_PATTERN VARCHAR(255) NOT NULL DEFAULT '.+';