CREATE TABLE `POLLS` (
  `POLL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
  `ENDING_DATE` datetime,
  `SINGLE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`POLL_ID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `POLL_OPTIONS` (
  `PO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `NAME` varchar(255) COLLATE utf8_bin NOT NULL,
  `VOTE_COUNT` int(11) NOT NULL DEFAULT '0',
  `POLL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PO_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_POLL` (`POLL_ID`),
  CONSTRAINT `FK_POLL` FOREIGN KEY (`POLL_ID`) REFERENCES `POLLS` (`POLL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `TOPIC`
	ADD COLUMN `POLL_ID` bigint(20) DEFAULT NULL;
ALTER TABLE `TOPIC`	
	ADD CONSTRAINT `FK_TOPIC_POLL` FOREIGN KEY (`POLL_ID`) REFERENCES `POLLS` (`POLL_ID`);