CREATE TABLE `SIMPLE_PAGE` (
  `PAGE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `NAME` longtext COLLATE utf8_bin NOT NULL UNIQUE,
  `PATH_NAME` longtext COLLATE utf8_bin NOT NULL,
  `POST_CONTENT` longtext COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`PAGE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;