CREATE TABLE `SECTION` (
  `SECTION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `NAME` varchar(255) COLLATE utf8_bin NOT NULL,
  `POSITION` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`SECTION_ID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `BRANCH` (
  `BRANCH_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `NAME` varchar(255) COLLATE utf8_bin NOT NULL,
  `DESCRIPTION` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BRANCHES_INDEX` int(11) DEFAULT NULL,
  `SECTION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`BRANCH_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_SECTION` (`SECTION_ID`),
  CONSTRAINT `FK_SECTION_REF` FOREIGN KEY (`SECTION_ID`) REFERENCES `SECTION` (`SECTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `BRANCH_SUBSCRIPTIONS` (
  `BRANCH_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  KEY `FK_USER` (`USER_ID`),
  KEY `FK_BRANCH` (`BRANCH_ID`),
  CONSTRAINT `FK_BRANCH_SUB` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCH` (`BRANCH_ID`),
  CONSTRAINT `FK_USER_BRANCH_SUB` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TOPIC` (
  `TOPIC_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
  `CREATION_DATE` datetime NOT NULL,
  `TOPIC_STARTER` bigint(20) NOT NULL,
  `BRANCH_ID` bigint(20) DEFAULT NULL,
  `TOPICS_INDEX` int(11) DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `TOPIC_WEIGHT` int(11) NOT NULL,
  `STICKED` tinyint(1) NOT NULL,
  `ANNOUNCEMENT` tinyint(1) NOT NULL,
  `VIEWS` int(11) DEFAULT '0',
  PRIMARY KEY (`TOPIC_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_TOPIC_STARTER` (`TOPIC_STARTER`),
  KEY `FK_BRANCH` (`BRANCH_ID`),
  CONSTRAINT `FK_BRANCH` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCH` (`BRANCH_ID`),
  CONSTRAINT `FK_TOPIC_STARTER` FOREIGN KEY (`TOPIC_STARTER`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `POST` (
  `POST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `POST_DATE` datetime NOT NULL,
  `POST_CONTENT` longtext COLLATE utf8_bin NOT NULL,
  `USER_CREATED` bigint(20) NOT NULL,
  `TOPIC_ID` bigint(20) DEFAULT NULL,
  `LIST_INDEX` int(11) DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`POST_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_USER` (`USER_CREATED`),
  KEY `FK_TOPIC` (`TOPIC_ID`),
  CONSTRAINT `FK_TOPIC` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`),
  CONSTRAINT `FK_USER` FOREIGN KEY (`USER_CREATED`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `PRIVATE_MESSAGE` (
  `PM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `USER_FROM` bigint(20) NOT NULL,
  `USER_TO` bigint(20) NOT NULL,
  `CREATION_DATE` datetime NOT NULL,
  `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
  `BODY` longtext COLLATE utf8_bin NOT NULL,
  `STATUS` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`PM_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_USER_TO` (`USER_TO`),
  KEY `FK_USER_FROM` (`USER_FROM`),
  CONSTRAINT `FK_USER_FROM` FOREIGN KEY (`USER_FROM`) REFERENCES `USERS` (`ID`),
  CONSTRAINT `FK_USER_TO` FOREIGN KEY (`USER_TO`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `TOPIC_SUBSCRIPTIONS` (
  `TOPIC_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  KEY `FK_USER` (`USER_ID`),
  KEY `FK_TOPIC` (`TOPIC_ID`),
  CONSTRAINT `FK_TOPIC_SUB` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`),
  CONSTRAINT `FK_USER_TOPIC_SUB` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JC_USER_DETAILS` (
  `USER_ID` bigint(20) NOT NULL,
  `SIGNATURE` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LANGUAGE` varchar(255) COLLATE utf8_bin DEFAULT 'ENGLISH',
  `PAGE_SIZE` int(11) DEFAULT '50',
  CONSTRAINT `FK_JC_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
