CREATE TABLE `POLLS` (
  `POLL_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(255) NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `ENDING_DATE` DATETIME,
  `SINGLE_ANSWER` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`POLL_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  CONSTRAINT `SHARED_PK_POLL_TOPIC` FOREIGN KEY (`POLL_ID`) REFERENCES `TOPIC` (`TOPIC_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `POLL_OPTIONS` (
  `PO_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `LIST_INDEX` INT(11) DEFAULT NULL,
  `VOTES_COUNT` INT(11) NOT NULL DEFAULT '0',
  `POLL_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`PO_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_POLL` (`POLL_ID`),
  CONSTRAINT `FK_POLL` FOREIGN KEY (`POLL_ID`) REFERENCES `POLLS` (`POLL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;