ALTER TABLE `JC_USER_DETAILS` ADD `LOCATION` varchar(255) COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE `JC_USER_DETAILS` ADD `REGISTRATION_DATE` datetime NOT NULL;
UPDATE `JC_USER_DETAILS` SET `REGISTRATION_DATE` = NOW();