ALTER TABLE BRANCH_SUBSCRIPTIONS DROP FOREIGN KEY FK_BRANCH_SUB;
ALTER TABLE BRANCH_SUBSCRIPTIONS ADD CONSTRAINT FK_BRANCH_SUB FOREIGN KEY (BRANCH_ID)
REFERENCES BRANCHES (BRANCH_ID) ON DELETE CASCADE;
