
UPDATE BRANCHES 
SET LAST_POST = (
    SELECT
           POST.POST_ID 
    FROM POST
    INNER JOIN (
      SELECT 
            TOPIC.BRANCH_ID, 
            MAX(POST.POST_DATE) as LAST_POST_TIME
      FROM POST
      INNER JOIN TOPIC 
            ON TOPIC.TOPIC_ID = POST.TOPIC_ID
      GROUP BY TOPIC.BRANCH_ID
    ) AS STATISTICS
            ON POST.POST_DATE = STATISTICS.LAST_POST_TIME
    WHERE BRANCHES.BRANCH_ID = STATISTICS.BRANCH_ID
)