CREATE TABLE `CODE_REVIEWS` (
    `CODE_REVIEW_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `UUID` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`CODE_REVIEW_ID`),
    UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDb DEFAULT CHARSET='utf8' COLLATE='utf8_bin';

CREATE TABLE `CODE_REVIEW_COMMENTS` (
    `COMMENT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `UUID` VARCHAR(255) NOT NULL,
    `LIST_INDEX` INT(11) DEFAULT NULL,
    `COMMENT` LONGTEXT NOT NULL,
    `LINE_NUMBER` INT NOT NULL,
    `AUTHOR` BIGINT(20) NOT NULL,
    `CODE_REVIEW_ID` BIGINT(20) NULL DEFAULT NULL,
    PRIMARY KEY (`COMMENT_ID`),
    UNIQUE INDEX `UUID` (`UUID`),
    INDEX `FK_CRC_CODE_REVIEW` (`CODE_REVIEW_ID`),
    INDEX `FK_CRC_AUTHOR` (`AUTHOR`),
    CONSTRAINT `FK_CRC_CODE_REVIEW` FOREIGN KEY (`CODE_REVIEW_ID`) 
        REFERENCES `CODE_REVIEWS` (`CODE_REVIEW_ID`) ON DELETE CASCADE,    
    CONSTRAINT `FK_CRC_AUTHOR` FOREIGN KEY (`AUTHOR`) 
        REFERENCES `USERS` (`ID`)
    
) ENGINE=InnoDb DEFAULT CHARSET='utf8' COLLATE='utf8_bin';

ALTER TABLE TOPIC ADD(CODE_REVIEW_ID bigint(20));
ALTER TABLE TOPIC ADD CONSTRAINT TOPIC_CODE_REVIEW_FK FOREIGN KEY(CODE_REVIEW_ID) 
    REFERENCES CODE_REVIEWS(CODE_REVIEW_ID);
