CREATE TABLE `CODE_REVIEW_SUBSCRIBER` (
  `CODE_REVIEW_ID` BIGINT(20) NOT NULL,
  `USER_ID`        BIGINT(20) NOT NULL,
  KEY `FK_USER` (`USER_ID`),
  KEY `FK_CODE_REVIEW` (`CODE_REVIEW_ID`),
  CONSTRAINT `FK_CODE_REVIEW_SUBSCRIBER` FOREIGN KEY (`CODE_REVIEW_ID`) REFERENCES `CODE_REVIEWS` (`CODE_REVIEW_ID`),
  CONSTRAINT `FK_USER_CODE_REVIEW_SUBSCRIBER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;