CREATE TABLE `CODE_REVIEW_SUBSCRIBER` (
  `CR_ID` BIGINT(20) NOT NULL,
  `USER_ID`        BIGINT(20) NOT NULL,
  KEY `FK_USER` (`USER_ID`),
  KEY `FK_CODE_REVIEW` (`CR_ID`),
  CONSTRAINT `FK_CODE_REVIEW_SUBSCRIBER` FOREIGN KEY (`CR_ID`) REFERENCES `CODE_REVIEWS` (`CR_ID`),
  CONSTRAINT `FK_USER_CODE_REVIEW_SUBSCRIBER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;