CREATE TABLE EXTERNAL_LINK (
  LINK_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  UUID VARCHAR(255) NOT NULL,
  URL VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  HINT VARCHAR(255) NOT NULL,
  PRIMARY KEY (LINK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
UPDATE EXTERNAL_LINK SET UUID = uuid();