CREATE TABLE `PLUGIN` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UUID` (`UUID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `PLUGIN_PROPERTY` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(255) NOT NULL,
  `TYPE` VARCHAR(255) NOT NULL,
  `VALUE` VARCHAR(255) NOT NULL,
  `LIST_INDEX` INT(11) DEFAULT NULL,
  `PLUGIN_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UUID` (`UUID`),
  KEY `FK_PLUGIN` (`PLUGIN_ID`),
  CONSTRAINT `FK_PLUGIN` FOREIGN KEY (`PLUGIN_ID`) REFERENCES `PLUGIN` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;