CREATE TABLE `MARK_BRANCH_AS_READ_TIME` (
  `ID`  bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) COLLATE utf8_bin NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `BRANCH_ID` bigint(20) NOT NULL,
  `MARKED_AS_READ_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`),
  UNIQUE KEY (`USER_ID`, `BRANCH_ID`),
  CONSTRAINT `FK_USER_READER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_READED_BRANCH` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCHES` (`BRANCH_ID`) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;