
CREATE TABLE POST_COMMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  UUID VARCHAR(255) NOT NULL,
  BODY LONGTEXT NOT NULL,
  CREATION_DATE DATETIME NOT NULL,
  AUTHOR_ID BIGINT(20) NOT NULL,
  POST_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (UUID),
  CONSTRAINT FK_COMMENT_POST FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID) ON DELETE CASCADE,
  CONSTRAINT FK_COMMENT_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID)
)ENGINE=InnoDb DEFAULT CHARSET='utf8' COLLATE='utf8_bin';

INSERT INTO POST_COMMENT (UUID, BODY, CREATION_DATE, AUTHOR_ID, POST_ID)
  SELECT UUID, BODY, CREATION_DATE, AUTHOR_ID,
    (SELECT POST_ID FROM POST p JOIN TOPIC t ON t.TOPIC_ID = p.TOPIC_ID WHERE t.CODE_REVIEW_ID=crc.CODE_REVIEW_ID)
  FROM CODE_REVIEW_COMMENTS crc;

CREATE TABLE TOPIC_ATTRIBUTE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  UUID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  TYPE VARCHAR(255) NOT NULL,
  VALUE LONGTEXT NOT NULL,
  TOPIC_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (UUID),
  UNIQUE KEY (NAME, TOPIC_ID),
  CONSTRAINT FK_TOPIC_PARAM FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID) ON DELETE CASCADE
)ENGINE=InnoDb DEFAULT CHARSET='utf8' COLLATE='utf8_bin';

CREATE TABLE COMMENT_ATTRIBUTE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  UUID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  TYPE VARCHAR(255) NOT NULL,
  VALUE LONGTEXT NOT NULL,
  COMMENT_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (UUID),
  UNIQUE KEY (NAME, COMMENT_ID),
  CONSTRAINT FK_COMMENT_PARAM FOREIGN KEY (COMMENT_ID) REFERENCES POST_COMMENT (ID) ON DELETE CASCADE
)ENGINE=InnoDb DEFAULT CHARSET='utf8' COLLATE='utf8_bin';

ALTER TABLE POST ADD RATING INT DEFAULT 0;

ALTER TABLE TOPIC ADD TYPE VARCHAR(255);

UPDATE TOPIC SET TYPE = 'Discussion' WHERE CODE_REVIEW_ID IS NULL;
UPDATE TOPIC SET TYPE = 'Code review' WHERE CODE_REVIEW_ID IS NOT NULL;

ALTER TABLE TOPIC
    MODIFY TYPE VARCHAR(255) NOT NULL;

INSERT INTO COMMENT_ATTRIBUTE (UUID, NAME, TYPE, VALUE, COMMENT_ID)
  SELECT (SELECT UUID() FROM dual), 'line_number', 'INT', CAST(LINE_NUMBER AS CHAR(255)),
    (SELECT ID FROM POST_COMMENT pc JOIN POST p ON pc.POST_ID = p.POST_ID
      JOIN TOPIC t ON p.TOPIC_ID = t.TOPIC_ID WHERE t.CODE_REVIEW_ID = crc.CODE_REVIEW_ID and crc.UUID = pc.UUID)
  FROM CODE_REVIEW_COMMENTS crc;