CREATE TABLE `POST_COMMENT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(255) NOT NULL,
  `BODY` LONGTEXT NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `COMMENT_INDEX` INT NOT NULL DEFAULT 0,
  `AUTHOR_ID` BIGINT(20) NOT NULL,
  `POST_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`UUID`),
  CONSTRAINT `FC_COMMENT_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
  CONSTRAINT `FC_COMMENT_AUTHOR` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `USERS` (`ID`)
)ENGINE=InnoDb DEFAULT CHARSET='utf8' COLLATE='utf8_bin';

INSERT INTO `POST_COMMENT` (`UUID`, `BODY`, `CREATION_DATE`, `COMMENT_INDEX`, `AUTHOR_ID`, `POST_ID`)
  SELECT `UUID`, `BODY`, `CREATION_DATE`, `LINE_NUMBER`, `AUTHOR_ID`,
    (SELECT `POST_ID` FROM `POST` p JOIN `TOPIC` t ON t.TOPIC_ID = p.TOPIC_ID WHERE t.CODE_REVIEW_ID=CRC.CODE_REVIEW_ID)
  FROM CODE_REVIEW_COMMENTS CRC;