-- Remove duplicates from LAST_READ_POSTS table
DELETE p FROM LAST_READ_POSTS AS p
  CROSS JOIN (SELECT ID
              FROM LAST_READ_POSTS
              GROUP BY ID
              HAVING COUNT(ID) > 1
             ) AS p2
  USING (ID);

ALTER TABLE LAST_READ_POSTS ADD UNIQUE INDEX `UNIQUE_TOPIC_ID_USER_ID` (TOPIC_ID, USER_ID);