ALTER TABLE POST_COMMENT ADD (
  MODIFICATION_DATE datetime DEFAULT NULL,
  USER_CHANGED BIGINT DEFAULT NULL,
  KEY FK_USER_CHANGED (USER_CHANGED),
  CONSTRAINT FK_USER_CHANGED FOREIGN KEY (USER_CHANGED) REFERENCES USERS (ID)
);
