ALTER TABLE `PRIVATE_MESSAGE` DROP FOREIGN KEY `FK_USER_TO`;
ALTER TABLE `PRIVATE_MESSAGE` MODIFY `USER_TO` bigint(20);
ALTER TABLE `PRIVATE_MESSAGE` MODIFY `TITLE` varchar(255) COLLATE utf8_bin;
ALTER TABLE `PRIVATE_MESSAGE` MODIFY `BODY` longtext COLLATE utf8_bin;